Python:
  beautifiers:
    - Black
    - YAPF
  wrap_line_length: 0
  indent_size: 4
  indent_style: space
Markdown:
  beautifiers:
    - Prettier
  pragma_insert: false
  pragma_require: false
  wrap_prose: never
